### ISSUE TITLE
Version 3.0.0-beta

### ISSUE THREAD

**Issue by DevNatan** [DevNatan/inventory-framework#370]
Pending tasks for version 3.0.0-beta
* [x] [Inter-view navigation](wiki/Navigating-Between-Views) documentation
* [x] Kyori's Adventure support on inventory title (#358).
* [x] `cancelOnDrag` configuration implementation (#363)
* [x] Fix target compatibility issues with non-JDK 8 projects (#366)
* [x] ~~Simplified version 2-like initial data (not `initialState(...)`, `context.get` and `context.set`)~~
* [x] Key change-based inventory updates (due to shared contexts poor performance) (#354)
* [x] #342 
* [x] #360 
* [x] ~~#345~~ (postponed)
* [x] ~~#339~~ (postponed)
* [x] #367

Version 2 issues that *may be* fixed in v3.0.0-EAP but need user testing
* [x] #278
* [x] #245

###### All v2.5. related issues *must be* resolved and tested in v3.0.0-EAP before v3.0.0-beta release.
